<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--需求:-->
<!--1.网络请求得到结果aaa,然后自己处理其他数据10行-->
<!--2.上一步的结果aaa,拼接一个111,然后自己处理其他数据10行-->
<!--3.同2的基础上在拼接一个222,然后自己处理其他数据10行-->

<script>

 //完整的写法
 // new Promise((resolve,reject) =>{
 //      setTimeout(() =>{
 //          resolve('aaa')
 //     },1000)
 // }).then(res =>{
 //    console.log('第一层10行代码')
 //     //对结果进行第一次处理
 //     return new Promise((resolve,reject) =>{  //如果只有一个resolve可以不写reject
 //        // resolve(res + '111')
 //         reject('err')  // reject的情况  找后面的catch
 //     })
 // }).then(res =>{
 //     console.log("第二层10行代码")
 //     return new Promise(resolve =>{  //如果只有一个resolve可以不写reject
 //         resolve(res + '222')
 //     })
 // }).then(res =>{
 //     console.log(res, '第3层10行代码')
 // }).catch(err =>{
 //     console.log(err)
 // })

//最后的简写
 new Promise((resolve,reject) =>{
     setTimeout(() =>{
         resolve('aaa')
     },1000)
 }).then(res =>{
     console.log('第一层10行代码')
     //对结果进行第一次处理
     // return new Promise(resolve =>{  //如果只有一个resolve可以不写reject
     //     resolve(res + '111')
     // })

     // 1. new Promise(resolve => resolve(结果)的简写
    //  return Promise.resolve(res + '111')


     //2. 最后的简写 省略掉Promise.resolve
     return res + '111'


     //reject的简写
    // return Promise.reject('err message')
     // throw 'err message' //手动异常


 }).then(res =>{
     console.log("第二层10行代码")
     // return new Promise(resolve =>{  //如果只有一个resolve可以不写reject
     //     resolve(res + '222')
     // })

     // return Promise.resolve(res + '222')
      return res + '222'
 }).then(res =>{
    console.log(res)
 }).catch(err =>{
     console.log(err)
 })


</script>

</body>
</html>